# Generated by Django 2.2.5 on 2019-10-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('context', models.TextField()),
                ('sneder_id', models.CharField(max_length=40)),
                ('sender_name', models.CharField(max_length=50)),
            ],
        ),
    ]
