# Generated by Django 2.2.5 on 2019-09-28 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('politics', models.CharField(max_length=50)),
                ('lifestyle', models.CharField(max_length=100)),
                ('markviews', models.IntegerField()),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('views', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
