# Generated by Django 2.2.5 on 2019-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments_parent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
